### ISSUE TITLE
Getter and Setter

### ISSUE THREAD

**Issue by chava-gnolasco** [calmarazs/InterestCalculator#1]
https://github.com/calmarazs/InterestCalculator/blob/6dd18b23f66b4ac079beae50af9f5c99da52528d/Calculator/src/main/java/mx/tis/com/application/dto/InitialInvestmentDto.java#L1

**Comment by chava-gnolasco** [comment]
Considera el uso de Lombok y el uso de las anotaciones: @Getter y @Setter, para evitar crear métodos para cada propiedad. 
***Nota: No esta mal la forma en la que lo hiciste, pero en caso de cambios el re-factor de estos pojos nos hacen perder el tiempo

**Comment by calmarazs** [comment]
Gracias por la observación. He agregado el uso de Lombok en mis DTOs para mejorar el codigo.
